# PUT http://localhost:3000/api/notes/1
# Content-Type: application/json

#   {
#     "content":"I love coding",
#     "date":"5/25/2021",
#     "important":false,
#     "id":1
#     }



POST http://localhost:3000/api/notes
Content-Type: application/json

{
    "content": "Another test for notes linked to users",
    "important": true,
    "date": "07/06/2021",
    "userId": "60bea5b2e5a0de102bc508cc"
}

# {
#     "notes": [],
#     "username": "daawa",
#     "name": "Theo Leveque",
#     "password": "WhistlerBaby"
# }