# PUT http://localhost:3000/api/notes/1
# Content-Type: application/json

#   {
#     "content":"I love coding",
#     "date":"5/25/2021",
#     "important":false,
#     "id":1
#     }



POST http://localhost:3000/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhYXdhIiwiaWQiOiI2MGJlYTViMmU1YTBkZTEwMmJjNTA4Y2MiLCJpYXQiOjE2MjMzNDc0OTV9.4v3jpGi1Ion3HESjYz-MCZ4h1fLrnnZ76Jy6Zb6rHPI

{
    "content": "Using token and bearer authorization",
    "important": true
}

# {
#     "username": "daawa",
#     "password": "WhistlerBaby",
# }

# {
#     "notes": [],
#     "username": "Flower",
#     "name": "Lily",
#     "password": "Whistler"
# }


# {
#     "content": "Another test for notes linked to users",
#     "important": true,
#     "date": "07/06/2021",
#     "userId": "60bea5b2e5a0de102bc508cc"
# }

# {
#     "notes": [],
#     "username": "daawa",
#     "name": "Theo Leveque",
#     "password": "WhistlerBaby"
# }